# Site settings
title: "Résumé | Hu Chenkai"
description: "Hu Chenkai's Résumé, built using Jekyll and GH Pages."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "HU Chenkai 胡宸恺 "
resume_title:                   "A CS Junior at ZJU"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "huchenkai0531@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+86 13735752882"
resume_contact_address:         "Yuquan Campus,Zhejiang University,Hangzhou"

resume_header_contact_info:     "Yuquan Campus,Zhejiang University,Hangzhou • +86 13735752882 • huchenkai0531@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>        I'm Hu Chenkai, now a junior at <a href='https://www.zju.edu.cn/english/'>Zhejiang University</a> majoring in Computer Science. I'm currently on my research internship at <a href='http://www.cad.zju.edu.cn/english.html'>CAD&CG State Key Lab</a> supervised by <a href='https://zhpcui.github.io/' >Prof. Zhaopeng Cui</a>. <br><br>My research interests include LLM/AIGC/CV/VR/XR... The <a href='https://github.com/chkhu/SRTP_city_digital_twin'>SRTP project</a> on metropolitan simulation UE5 models that I'm leading is making steady progress. 👉View my <a href='https://chkhu.github.io/'>homepage</a>.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_projects:        true
resume_section_experience:      true
resume_section_education:       true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/chkhu"
  resume_twitter_url:           "https://twitter.com/HUCKK123"
  resume_linkedin_url:          "https://www.linkedin.com/in/chenkai-hu-984459245/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://chkhu.github.io/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
